name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node: [16, 18]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: latest
    - uses: actions/setup-node@v3.7.0
      with:
        node-version: ${{ matrix.node }}
        cache: 'pnpm'
    - name: PNPM Install
      run: pnpm install
    - name: Build
      run: pnpm run build
    - name: Test
      run: pnpm test