name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node: [18, 20]
    steps:
    - uses: actions/checkout@v5
    - uses: pnpm/action-setup@v4
      with:
        version: latest
    - uses: actions/setup-node@v5.0.0
      with:
        node-version: ${{ matrix.node }}
        cache: 'pnpm'
    - name: PNPM Install
      run: pnpm install
    - name: Build
      run: pnpm run build
    - name: Test
      run: pnpm test